# Generated by Django 5.0.6 on 2026-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='poll_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='ecocash_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
